services:
  printscript-ui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_AUTH0_DOMAIN: ${VITE_AUTH0_DOMAIN}
        VITE_AUTH0_CLIENT_ID: ${VITE_AUTH0_CLIENT_ID}
        VITE_AUTH0_AUDIENCE: ${VITE_AUTH0_AUDIENCE}
        VITE_AUTH0_CALLBACK_URL: ${VITE_AUTH0_CALLBACK_URL}
        VITE_PERMISSION_BASE_URL: ${VITE_PERMISSION_BASE_URL}
    ports:
      - "5173:80"
